### PR TITLE
140. Adding column count limit

### LINKED ISSUE #140: Limit number of columns
### Problem

Currently, a mistake in the code can generate an endless number of columns in the database.

### Solution

Let's have a setting `max_columns` (per destination) that is 100 by default. If during schema patching number of columns has exceeded, let's fail the whole process - row or whole batch.

### PR DESCRIPTION
**Pull request by Alessar**
Fixes #140 
* Adding server.max_columns setting
* Adding column count calculation
* Adding preventing increasing columns in databases
* Adding data_layout.max_columns setting
* Adding overriding behaviour for max_columns settings.

### CODE REVIEW

File: server/storages/bigquery.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func NewBigQuery(config *Config) (Storage, error) {
 		return nil, err
 	}
 
-	tableHelper := NewTableHelper(bigQueryAdapter, config.monitorKeeper, config.pkFields, adapters.SchemaToBigQueryString, config.streamMode)
+	tableHelper := NewTableHelper(bigQueryAdapter, config.monitorKeeper, config.pkFields, adapters.SchemaToBigQueryString, config.streamMode, config.max_columns)
```
Comment (vklimontovich) [inline server/storages/bigquery.go:75]: Shouldn't it be maxColumns instead of max_columns?

File: server/config/config.template.yaml [hunk 2]
```diff
@@ -40,6 +40,11 @@ server:
   ### Public URL. It is used in welcome.html if not configured it will be taken from 'Host' http header on welcome.html requests
   #public_url: https://yourhost #Optional.
 
+  ### Limit the count of columns for any destinations.
+  ### It helps to prevent generating an infinite amount of columns in databases.
+  ### Zero value turns off column count calculation.
+  max_columns: 100 #Optional
```
Comment (xtreding) [inline server/config/config.template.yaml:46]: I think it would be better to have this flag on the destination configuration level (in `data_layout` section). 
```
destinations:
  pg:
   ...
    data_layout:
      max_columns: 100
```
The logic might be:
- if a destination doesn't have configured `max_columns` - apply default value = `100`

File: server/storages/bigquery.go (hunk 1 above)
Comment (xtreding) [reply server/storages/bigquery.go:75]: Absolutely

File: server/storages/table_helper.go [hunk 3]
```diff
@@ -26,11 +26,12 @@ type TableHelper struct {
 	pkFields           map[string]bool
 	columnTypesMapping map[typing.DataType]string
 
-	streamMode bool
+	streamMode  bool
+	max_columns int
```
Comment (xtreding) [inline server/storages/table_helper.go:30]: `max_columns` -> `maxColumns`

File: server/storages/table_helper.go [hunk 4]
```diff
@@ -88,6 +90,14 @@ func (th *TableHelper) EnsureTable(destinationName string, dataSchema *adapters.
 		return dbSchema, nil
 	}
 
+	if th.max_columns > 0 {
+		columns_count := len(dbSchema.Columns) + len(diff.Columns)
+		if columns_count > th.max_columns {
+			msg := fmt.Sprintf("Count of columns %d should be less or equal max_columns %d", columns_count, th.max_columns)
```
Comment (xtreding) [inline server/storages/table_helper.go:96]: return `fmt.Errorf("", ...)` could be used here.

**Review by xtreding — CHANGES_REQUESTED** [review]

File: server/config/config.template.yaml (hunk 2 above)
Comment (Alessar) [reply server/config/config.template.yaml:46]: It was already mentioned at the [issue](https://github.com/jitsucom/jitsu/issues/140#issuecomment-803409720).
It looks like a simple error checking.
Will it be different for different destinations?
If not - it can be used just for simple checking.

File: server/storages/table_helper.go (hunk 3 above)
Comment (Alessar) [reply server/storages/table_helper.go]: Renamed

File: server/storages/table_helper.go (hunk 4 above)
Comment (Alessar) [reply server/storages/table_helper.go]: Changed

File: server/storages/bigquery.go (hunk 1 above)
Comment (Alessar) [reply server/storages/bigquery.go:75]: Renamed

File: server/config/config.template.yaml (hunk 2 above)
Comment (Alessar) [reply server/config/config.template.yaml]: Fixed.
To error checking, an option is used on the server level if it is positive.
Any destination can override that setting by any positive value.

File: server/config/config.template.yaml [hunk 5]
```diff
@@ -40,6 +40,12 @@ server:
   ### Public URL. It is used in welcome.html if not configured it will be taken from 'Host' http header on welcome.html requests
   #public_url: https://yourhost #Optional.
 
+  ### Limit the count of columns for any destinations.
+  ### It helps to prevent generating an infinite amount of columns in databases.
+  ### Zero value turns off the column count calculation.
+  ### It can be overridden at the destination level only by a positive value.
+  max_columns: 100 # Optional
```
Comment (xtreding) [inline server/config/config.template.yaml:47]: We shouldn't have global value for `max_columns`

File: server/main.go [hunk 6]
```diff
@@ -293,7 +293,9 @@ func main() {
 		logging.Warnf("Global users recognition isn't configured")
 	}
 
-	destinationsFactory := storages.NewFactory(ctx, logEventPath, coordinationService, eventsCache, loggerFactory, globalRecognitionConfiguration)
+	maxColumns := viper.GetInt("server.max_columns")
```
Comment (xtreding) [inline server/main.go:296]: We shouldn't have global value for `max_columns`

File: server/storages/facebook.go [hunk 7]
```diff
@@ -39,7 +39,7 @@ func NewFacebook(config *Config) (Storage, error) {
 	requestDebugLogger := config.loggerFactory.CreateSQLQueryLogger(config.name)
 	fbAdapter := adapters.NewFacebookConversion(fbConfig, requestDebugLogger)
 
-	tableHelper := NewTableHelper(fbAdapter, config.monitorKeeper, config.pkFields, adapters.SchemaToFacebookConversion, config.streamMode)
+	tableHelper := NewTableHelper(fbAdapter, config.monitorKeeper, config.pkFields, adapters.SchemaToFacebookConversion, config.streamMode, config.maxColumns)
```
Comment (xtreding) [inline server/storages/facebook.go:42]: We shouldn't have max_columns for facebook (because facebook doesn't have columns)

File: server/storages/factory.go [hunk 8]
```diff
@@ -145,6 +151,10 @@ func (f *FactoryImpl) Create(name string, destination DestinationConfig) (Storag
 		for _, field := range destination.DataLayout.PrimaryKeyFields {
 			pkFields[field] = true
 		}
+
+		if destination.DataLayout.MaxColumns > 0 {
```
Comment (xtreding) [inline server/storages/factory.go:155]: There must be a default value = 100, and the destination can override it.

File: server/storages/google_analytics.go [hunk 9]
```diff
@@ -39,7 +39,7 @@ func NewGoogleAnalytics(config *Config) (Storage, error) {
 	requestDebugLogger := config.loggerFactory.CreateSQLQueryLogger(config.name)
 	gaAdapter := adapters.NewGoogleAnalytics(gaConfig, requestDebugLogger)
 
-	tableHelper := NewTableHelper(gaAdapter, config.monitorKeeper, config.pkFields, adapters.SchemaToGoogleAnalytics, config.streamMode)
+	tableHelper := NewTableHelper(gaAdapter, config.monitorKeeper, config.pkFields, adapters.SchemaToGoogleAnalytics, config.streamMode, config.maxColumns)
```
Comment (xtreding) [inline server/storages/google_analytics.go:42]: We shouldn't have max_columns for google analytics (because google analytics doesn't have columns)

**Review by xtreding — CHANGES_REQUESTED** [review]

File: server/storages/facebook.go (hunk 7 above)
Comment (Alessar) [reply server/storages/facebook.go]: Zero was set for facebook destination type

File: server/storages/google_analytics.go (hunk 9 above)
Comment (Alessar) [reply server/storages/google_analytics.go]: Zero was set for google analitics destination type

File: server/storages/factory.go (hunk 8 above)
Comment (Alessar) [reply server/storages/factory.go:155]: Message was added

File: server/config/config.template.yaml (hunk 5 above)
Comment (Alessar) [reply server/config/config.template.yaml:47]: * `100` in the code - it looks like the magic number and it cannot be changed.
* Configuration settings provide a better description and provide the capability to change it.
* There is the capability to make `self-hosted` installation.
It is better to use one single option than several options, if admins want to change such setting.

**Review by xtreding — APPROVED** [review]
